# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-03 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='content',
            field=models.CharField(default='This is content', max_length=2000),
            preserve_default=False,
        ),
    ]
