# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-03 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_indexcontent_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='description',
            field=models.CharField(default='This is a new promotion', max_length=500),
            preserve_default=False,
        ),
    ]
