# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_newsimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcontent',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
