# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_dress_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=2000)),
                ('product_type', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
    ]
