# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_indexproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexproduct',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni')], max_length=20),
        ),
    ]
