# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20171104_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni')], max_length=20),
        ),
    ]
