# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_skjorte_sko_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapImage', models.FileField(upload_to=b'')),
                ('address', models.TextField(max_length=3000)),
                ('info', models.FileField(upload_to=b'')),
                ('job', models.TextField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='tip',
            name='tip_text',
            field=models.TextField(max_length=3000),
        ),
    ]
