# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20171116_0544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Contact',
        ),
    ]
