# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-29 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_collection_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Klokke',
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dress',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett')], max_length=20),
        ),
        migrations.AlterField(
            model_name='indexproduct',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mansjett',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seremoni',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skjorte',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sko',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett')], max_length=20),
        ),
        migrations.AlterField(
            model_name='slips',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smoking',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett')], max_length=20),
        ),
    ]
