# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20171129_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sloyfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=2000)),
                ('product_type', models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20)),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dress',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='indexproduct',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mansjett',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seremoni',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skjorte',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sko',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='slips',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smoking',
            name='product_type',
            field=models.CharField(choices=[(b'dress', b'dress'), (b'seremoni', b'seremoni'), (b'skjorte', b'skjorte'), (b'sko', b'sko'), (b'smoking', b'smoking'), (b'slip', b'slip'), (b'mansjett', b'mansjett'), (b'sloyfe', b'sloyfe')], max_length=20),
        ),
    ]
